### PR TITLE
[WIP] Refactoring to use Babel (node5) and support for Koa 2.0

### PR DESCRIPTION
**Pull request by mekwall**
I've begun refactoring the code to use the same syntax as Koa 2.0. It seems to work atm. but I would love to get some people to test this out. Also need to fix the tests since they are currently broken.

Any feedback is welcome!

### CODE REVIEW

**Comment by uptownhr** [comment]
any progress here?

**Comment by PengXing** [comment]
any progress?

**Comment by mekwall** [comment]
Anyone else is welcome to pick this up. I don't use this package anymore. Sorry!

**Comment by nsimmons** [comment]
Can be closed now that #123 is merged

**Comment by niftylettuce** [comment]
See v2.x - will be published later today

**Pull request closed without merging**
