### PR TITLE
Refactor to koa 2 - Supports node 6.x and 7.x

### PR DESCRIPTION
**Pull request by nsimmons**
This PR is a combination of https://github.com/koajs/generic-session/pull/122 and https://github.com/koajs/generic-session/pull/81.

The code is written to use async / await to match Koa 2 middleware style, but uses babel to convert the syntax to be compatible with node 6.9.0+ being the official LTS version of node. I think it's important for this module to support v6 of node, and also be ready to use async / await syntax as soon as the next LTS version of node supports it. 

This PR adds an additional step that `make build` must be run before publishing.

### CODE REVIEW

**Comment by nsimmons** [comment]
@dead-horse Could i get some 👀  on this?

**Comment by niftylettuce** [comment]
looks good here

**Comment by nsimmons** [comment]
Awesome. I'll rebase this PR ASAP so it can get merged.

**Comment by nsimmons** [comment]
This is ready to go. @niftylettuce you good to merge this and release?

**Comment by nsimmons** [comment]
Anyone able to merge this PR? CI says pending here but it's green if you click through.

**Comment by niftylettuce** [comment]
Nice work, let me test it later today and I'll accept/merge/publish

**Comment by niftylettuce** [comment]
@nsimmons OK taking a look now, sorry for delay!

**Comment by nsimmons** [comment]
Thanks for taking a look! Glad to see this will ship now. 👏

**Comment by niftylettuce** [comment]
@nsimmons should we also update badge for Node in Readme?  And should we provide clearer docs for older version support?  e.g. we now have `new koa()` and prior to that I don't think we did

**Comment by nsimmons** [comment]
mm yes i will take a look

**Comment by dead-horse** [comment]
@niftylettuce what's your npm name?

and you should update History.md before publish 2.0.0

**Comment by niftylettuce** [comment]
@dead-horse it's "niftylettuce" on NPM

**Comment by dead-horse** [comment]
added

**Comment by niftylettuce** [comment]
thanks @dead-horse - I went ahead and updated History.md and released new version to NPM at v2.0.0 cc @nsimmons - please ensure it works in production from NPM for you as well!

**Comment by nsimmons** [comment]
Will upgrade today and will open an issue if I find anything. Thanks!

**Pull request merged**
