### PR TITLE
fix: always refresh session

### LINKED ISSUE #93: Save session even if an error occur
Because of this line https://github.com/koajs/generic-session/blob/f042b55429b3c0ff06588143d4984c3dc82e6cf7/lib/session.js#L338-L339

the session is only saved when no errors are thrown

### PR DESCRIPTION
**Pull request by dead-horse**
closes #93 #94

### CODE REVIEW

**Comment by dead-horse** [comment]
1.11.3

**Comment by niftylettuce** [comment]
thank you!!!!

**Comment by niftylettuce** [comment]
@dead-horse @fengmk2 can you please do an `npm deprecate` notice for people using prior versions?  this is a big bug, especially for those that use flash messaging.

**Comment by niftylettuce** [comment]
@dead-horse @fengmk2 I still think this is broken.  If you do a `ctx.redirect` right after setting a new setting property, such as `ctx.session.foo = 'bar';`, then the next time the session loads, `ctx.session.foo` is undefined and the session didn't save.

**Pull request merged**
