### PR TITLE
Also reset '.sig' cookie

### PR DESCRIPTION
**Pull request by catamphetamine**

### CODE REVIEW

**Comment by DaAwesomeP** [comment]
Should we add a test?

**Comment by halt-hammerzeit** [comment]
Yeah, this could benefit from a test
https://github.com/koajs/generic-session/blob/master/test/session.test.js#L59

Currently too busy though.

**Comment by niftylettuce** [comment]
Can you please update your source code and modify the `src` directory instead?  I would accept a PR.

**Comment by niftylettuce** [comment]
See previous comment - feel free to submit a new PR if you still use this.

**Pull request closed without merging**
